### ISSUE TITLE
Struktur Menu dan Pencarian

### ISSUE THREAD

**Issue by Mazrielyaqiakbar** [Mazrielyaqiakbar/uas-struktur-data#1]

**Comment by Pentongnur** [comment]
[clearrr.txt](https://github.com/user-attachments/files/18216869/clearrr.txt)

**Comment by khansafawwazyadna** [comment]
[Menu 1.txt](https://github.com/user-attachments/files/18216911/Menu.1.txt)
[Menu 2.txt](https://github.com/user-attachments/files/18216912/Menu.2.txt)
