### ISSUE TITLE
Program Utama dan Integrasi

### ISSUE THREAD

**Issue by Mazrielyaqiakbar** [Mazrielyaqiakbar/uas-struktur-data#5]

**Comment by Pentongnur** [comment]
int main() {
    TreeNode *menuTree = NULL;
    Queue *antrianPesanan = buatQueue();
    int pilihan;

    do {
        tampilkanMenuUtama();
        scanf("%d", &pilihan);

        switch(pilihan) {
            case 1:
                handleInputMenu();
                break;
            case 2:
                printf("\nDaftar Menu:\n");
                tampilkanMenu(menuTree);
                break;
            case 3:
                handlePesanan();
                break;
            case 4:
                handleAntrian();
                break;
            case 5:
                tampilkanLaporan();
                break;
            case 6:
                printf("Terima kasih telah menggunakan sistem!\n");
                break;
            default:
                handleError("Pilihan tidak valid!");
        }
    } while (pilihan != 6);

    return 0;
}

**Comment by Pentongnur** [comment]
[popopo.txt](https://github.com/user-attachments/files/18213376/popopo.txt)

**Comment by Pentongnur** [comment]
[clearrr.txt](https://github.com/user-attachments/files/18213390/clearrr.txt)
